version: '3.8'

#write a docker compose file for a postgres database
services:

  jsonserver:
    container_name: jsonserver
    build: ./jsonServer
    ports:
      - '9000:9000'
    volumes:
      - ./jsonServer:/app
      - /app/node_modules

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules