version: '3.8'

#write a docker compose file for a postgres database
services:

  jsonserver:
    container_name: jsonserver
    build: ./jsonServer
    ports:
      - '9000:9000'
    volumes:
      - ./jsonServer:/app
      - /app/node_modules

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  sqldb:
    container_name: sqldb
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - sqldb_data:/var/lib/postgresql/data

volumes:
  sqldb_data: